"""Scanner runtime configuration (non-secret values only)."""

import json
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent
LOG_DIR = ROOT_DIR / "logs"
REPORT_DIR = ROOT_DIR / "reports"
EVIDENCE_DIR = REPORT_DIR / "evidence"
TUNING_DIR = ROOT_DIR / "tuning"
OVERRIDES_PATH = TUNING_DIR / "overrides.json"
EDGE_INDEX_PATH = REPORT_DIR / "edge_retrieval_index.json"
EDGE_SCAN_REPORT_PATH = REPORT_DIR / "edge_scan_report.json"
EDGE_VALIDATION_REPORT_PATH = REPORT_DIR / "edge_validation_report.json"
EDGE_DIAGNOSTIC_REPORT_PATH = REPORT_DIR / "edge_diagnostic_report.json"
EDGE_AUDIT_REPORT_PATH = REPORT_DIR / "edge_audit_report.json"

MIN_STOCK_PRICE = 5.00
MIN_KRONOS_AGREEMENT = 0.65
MIN_RR = 1.5
MIN_EMPTY_SPACE_SCORE = 2
EARNINGS_BLOCK_DAYS = 10
BLOCK_ON_UNKNOWN_EARNINGS = True
BLOCK_ON_EX_DIVIDEND = False
MIN_ATM_OPEN_INTEREST = 500
MAX_ATM_BID_ASK_SPREAD_PCT = 0.12
CONSOLIDATION_BARS = 15
ATR_PERIOD = 14
ATR_COMPRESSION = 0.75
RANGE_COMPRESSION = 0.65
NO_TREND_SLOPE_ABS_MAX = 0.0015
MIN_BOX_TOP_TOUCHES = 2
MIN_BOX_BOTTOM_TOUCHES = 2
BOX_TOUCH_TOLERANCE_PCT = 0.0015
USE_CLOSE_BASED_CONTROL = True
RESEARCH_CANDIDATE_MIN_SCORE = 62
RESEARCH_NEAR_BREAKOUT_PCT = 0.012
RESEARCH_MIN_VOLUME_EXPANSION = 1.15
PRED_DAYS = 5
DRY_RUN_DEFAULT = True

INTRADAY_INTERVAL = "30m"
INTRADAY_LOOKBACK = "60d"
DAILY_PROXY_LOOKBACK = "2y"
MARKET_DATA_PROVIDER_DEFAULT = "auto"  # auto | alpaca | yfinance
ALPACA_FEED = "iex"  # iex (free) or sip (subscription)

SYNTHETIC_SESSION_ANCHOR_HOUR = 20
SYNTHETIC_SESSION_ANCHOR_MINUTE = 0
TIMEZONE = "America/New_York"

KRONOS_MODEL_NAME = "NeoQuasar/Kronos-small"
KRONOS_TOKENIZER_NAME = "NeoQuasar/Kronos-Tokenizer-base"
KRONOS_LOOKBACK_BARS = 60
KRONOS_SAMPLE_COUNT = 10

MINIMAX_ENABLED_DEFAULT = False
MINIMAX_MODEL = "MiniMax-M2.7-highspeed"
MINIMAX_BASE_URL = "https://api.minimax.io/v1"
MINIMAX_TIMEOUT_SECONDS = 20
MINIMAX_MAX_OUTPUT_TOKENS = 220
MINIMAX_TEMPERATURE = 0.2

CALIBRATION_PASS_AVG_ABS_MAX = 0.35
CALIBRATION_WARN_AVG_ABS_MAX = 0.90
CALIBRATION_MIN_MATCHED_ROWS = 20

TUNING_ENABLED_DEFAULT = True
OUTCOME_REVIEW_MAX_RECORDS = 500
OUTCOME_MIN_AGE_DAYS = 3
AUTOTUNE_MIN_SAMPLES = 20
AUTOTUNE_STEP_SIZE = 0.05
AUTOTUNE_EMPTY_SPACE_STEP = 1
EDGE_ANALOG_K = 7
EDGE_EMBARGO_DAYS = 5
EDGE_MIN_ANALOGS = 3
EDGE_VALIDATION_MAX_RECORDS = 600
EDGE_VALIDATION_THRESHOLDS = (45, 55, 65)

MIN_RR_BOUNDS = (1.1, 2.5)
MIN_KRONOS_AGREEMENT_BOUNDS = (0.50, 0.85)
MIN_EMPTY_SPACE_SCORE_BOUNDS = (1, 3)
MAX_ATM_BID_ASK_SPREAD_PCT_BOUNDS = (0.08, 0.25)
MIN_ATM_OPEN_INTEREST_BOUNDS = (200, 3000)
ATR_COMPRESSION_BOUNDS = (0.55, 1.10)
RANGE_COMPRESSION_BOUNDS = (0.45, 1.05)
NO_TREND_SLOPE_ABS_MAX_BOUNDS = (0.0008, 0.0040)
RESEARCH_CANDIDATE_MIN_SCORE_BOUNDS = (45, 80)

DEFAULT_WATCHLIST = [
    "SOFI", "MARA", "RIOT", "HIMS", "TTD",
    "SOUN", "UPST", "SNAP", "LYFT", "RIVN",
    "GME", "AAL", "CCL", "PFE", "T",
    "F", "KEY", "OPEN", "CHPT", "NIO",
    "CLSK", "CIFR", "LUNR", "BBAI", "EVGO",
    "PLTR", "HOOD", "RKLB", "AFRM", "IONQ",
]


def _apply_overrides():
    global MIN_RR
    global MIN_KRONOS_AGREEMENT
    global MIN_EMPTY_SPACE_SCORE
    global MAX_ATM_BID_ASK_SPREAD_PCT
    global MIN_ATM_OPEN_INTEREST
    global ATR_COMPRESSION
    global RANGE_COMPRESSION
    global NO_TREND_SLOPE_ABS_MAX
    global RESEARCH_CANDIDATE_MIN_SCORE

    if not OVERRIDES_PATH.exists():
        return
    try:
        payload = json.loads(OVERRIDES_PATH.read_text(encoding="utf-8"))
    except Exception:
        return
    if not isinstance(payload, dict):
        return

    if "MIN_RR" in payload:
        MIN_RR = float(payload["MIN_RR"])
    if "MIN_KRONOS_AGREEMENT" in payload:
        MIN_KRONOS_AGREEMENT = float(payload["MIN_KRONOS_AGREEMENT"])
    if "MIN_EMPTY_SPACE_SCORE" in payload:
        MIN_EMPTY_SPACE_SCORE = int(payload["MIN_EMPTY_SPACE_SCORE"])
    if "MAX_ATM_BID_ASK_SPREAD_PCT" in payload:
        MAX_ATM_BID_ASK_SPREAD_PCT = float(payload["MAX_ATM_BID_ASK_SPREAD_PCT"])
    if "MIN_ATM_OPEN_INTEREST" in payload:
        MIN_ATM_OPEN_INTEREST = int(payload["MIN_ATM_OPEN_INTEREST"])
    if "ATR_COMPRESSION" in payload:
        ATR_COMPRESSION = float(payload["ATR_COMPRESSION"])
    if "RANGE_COMPRESSION" in payload:
        RANGE_COMPRESSION = float(payload["RANGE_COMPRESSION"])
    if "NO_TREND_SLOPE_ABS_MAX" in payload:
        NO_TREND_SLOPE_ABS_MAX = float(payload["NO_TREND_SLOPE_ABS_MAX"])
    if "RESEARCH_CANDIDATE_MIN_SCORE" in payload:
        RESEARCH_CANDIDATE_MIN_SCORE = int(payload["RESEARCH_CANDIDATE_MIN_SCORE"])


_apply_overrides()
